config/routes.rb
Rails.application.routes.draw do
  resources :baths
  get 'baths/home'
  root 'baths#home'
  get 'info/result'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bath.rb
class Bath < ApplicationRecord
end

app/models/restroom_database.rb
class RestroomDatabase < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/baths_controller.rb
class BathsController < ApplicationController
  before_action :set_bath, only: [:show, :edit, :update, :destroy]

  # GET /baths
  # GET /baths.json

  # def lat
  #   @_lat ||= session[:lat] &&
  #     Bath.find_by(id: session[:lat])
  # end
  
  # def lon
  #   @_lon ||= session[:lon] &&
  #     Bath.find_by(id: session[:lon])
  # end

  def home
    @baths= Bath.all
    
  end

  def index
    @baths = Bath.all
  end

  # GET /baths/1
  # GET /baths/1.json
  def show
  end

  # GET /baths/new
  def new
    @bath = Bath.new
  end

  # GET /baths/1/edit
  def edit
  end

  # POST /baths
  # POST /baths.json
  def create
    @bath = Bath.new(bath_params)

    respond_to do |format|
      if @bath.save
        format.html { redirect_to @bath, notice: 'Bath was successfully created.' }
        format.json { render :show, status: :created, location: @bath }
      else
        format.html { render :new }
        format.json { render json: @bath.errors, status: :unprocessable_entity }
      end
      # redirect_to root_path(lat: @lat)
      # redirect_to root_path(lon: @lon)
    end

    # if lat = Bath.authenticate(params[:lat])
    #   session[:lat] = lat.id
    #   redirect_to root_url
    # end

    # if lon = Bath.authenticate(params[:lon])
    #   session[:lon] = lon.id
    #   redirect_to root_url
    # end
  end

  # PATCH/PUT /baths/1
  # PATCH/PUT /baths/1.json
  def update
    respond_to do |format|
      if @bath.update(bath_params)
        format.html { redirect_to @bath, notice: 'Bath was successfully updated.' }
        format.json { render :show, status: :ok, location: @bath }
      else
        format.html { render :edit }
        format.json { render json: @bath.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /baths/1
  # DELETE /baths/1.json
  def destroy
    @bath.destroy
    respond_to do |format|
      format.html { redirect_to baths_url, notice: 'Bath was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bath
      @bath = Bath.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bath_params
      params.require(:bath).permit(:name, :lat, :lon, :clean, :handicapped, :near, :supplies)
    end

end

app/controllers/info_controller.rb
class InfoController < ApplicationController
  def result

#거리 quicksort한 결과
    def quicksort(x)
        if len(x) == 1
            return x
        end
        pivot = x[len(x)/2]
            less = []
            more = []
        for a in (x)
            if (a < pivot)
                less.append(a)
            elsif (a > pivot)
                more.append(a)
            else
                equal = [a]
            end
        end
    return quicksort(less) + equal + quicksort(more)
    end

#'적절한' 화장실 가중치 부여
    def goodness(x)
        @clean=session[:clean].to_i
        @near=session[:near].to_i
        @supply=session[:supplies].to_i

        return @clean * @near * @supply
    end
        

    @curLat=params[:curLat].to_f
    @curLon=params[:curLon].to_f

    lat = session[:lat].to_a
    lon = session[:lon].to_a

    len = []

    lat.each do |i|
        lon.each do |o|
        if lat(i) > @curLat
                dis_lat = ( lat(i) - @curLat)
        else
            dis_lat = ( @curLat - lat(i) )
        end

        if lon(o) > @curLon
                dis_lon = ( lon(o) - @curLon)
        else
            dis_lon = ( @curLon - lon(o))
        end

        goodness = goodness()

        k = (dis_lat + dis_lon) * goodness
        len << k
        
        end
    end
    
    distance = quicksort()
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/baths_helper.rb
module BathsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/info_helper.rb
module InfoHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/baths/_form.html.erb
<%= form_with(model: bath, local: true) do |form| %>
  <% if bath.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bath.errors.count, "error") %> prohibited this bath from being saved:</h2>

      <ul>
      <% bath.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :bath_name %>
  </div>

  <div class="field">
    <%= form.label :lat %>
    <%= form.text_field :lat, id: :bath_lat %>
  </div>

  <div class="field">
    <%= form.label :lon %>
    <%= form.text_field :lon, id: :bath_lon %>
  </div>

  <div class="field">
    <%= form.label :clean %>
    <%= form.number_field :clean, id: :bath_clean %>
  </div>

  <div class="field">
    <%= form.label :handicapped %>
    <%= form.number_field :handicapped, id: :bath_handicapped %>
  </div>

  <div class="field">
    <%= form.label :near %>
    <%= form.number_field :near, id: :bath_near %>
  </div>

  <div class="field">
    <%= form.label :supplies %>
    <%= form.number_field :supplies, id: :bath_supplies %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/baths/edit.html.erb
<h1>Editing Bath</h1>

<%= render 'form', bath: @bath %>

<%= link_to 'Show', @bath %>
<%= link_to 'Back', baths_path %>

app/views/baths/home.html.erb
<!DOCTYPE html> 
<html> 
<head> 
  <title>2017120163_방혜주</title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"> 
</head>
<body> 

 <!DOCTYPE html> 
<html> 
<head> 
  <title>화슐랭</title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"> 
</head>
<body> 
 
  <h1>Welcome to KU Science Campus</h1>
  <h3>If you need this service, just RUN!</h3>
  <div id="tripmeter"> 
    <p> 
      Current Location: <span id="currentLat"></span>°, <span id="currentLon"></span>°
    </p>

  <form action="info/result" name="curLocation" method="get">
    Tell me where you are: <br>
    <input type="integer" name="curLat" placeholder="Latitude" required />°,
    <input type="integer" name="curLon" placeholder="Longitude" required/>° <input type="submit" name="submit" title="submit" /> <input type="reset" name="reset" title="reset"/><br><br>
  </fieldset>
  </form>

  <%= link_to "List", baths_path %>

</div>

  <script> 
    window.onload = function() {
      var startPos;
       
      if (navigator.geolocation) { 
        navigator.geolocation.getCurrentPosition(function(position) {
          startPos = position;
          document.getElementById("startLat").innerHTML = startPos.coords.latitude;
          document.getElementById("startLon").innerHTML = startPos.coords.longitude;
        }, function(error) {
          alert("Error occurred. Error code: "+error.code);
        });
    
        navigator.geolocation.watchPosition(function(position) {
          document.getElementById("currentLat").innerHTML = position.coords.latitude;
          document.getElementById("currentLon").innerHTML = position.coords.longitude;
          document.getElementById("distance").innerHTML =
            calculateDistance(startPos.coords.latitude, startPos.coords.longitude,
                              position.coords.latitude, position.coords.longitude);
        });
      }
    };
    // Reused code - copyright Moveable Type Scripts - retrieved May 4, 2010.
    // http://www.movable-type.co.uk/scripts/latlong.html
    // Under Creative Commons License http://creativecommons.org/licenses/by/3.0/
    function calculateDistance(lat1, lon1, lat2, lon2) {
      var R = 6371; // km
      var dLat = (lat2-lat1).toRad();
      var dLon = (lon2-lon1).toRad(); 
      var a = Math.sin(dLat/2) * Math.sin(dLat/2) +
              Math.cos(lat1.toRad()) * Math.cos(lat2.toRad()) * 
              Math.sin(dLon/2) * Math.sin(dLon/2); 
      var c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a)); 
      var d = R * c;
      return d;
    }
    Number.prototype.toRad = function() {
      return this * Math.PI / 180;
    }
  </script> 

</body>
</html>

app/views/baths/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Where is Toliet?</h1>

<table>
  <thead class="hi">
    <tr>
      <th>Name</th>
      <th>Lat</th>
      <th>Lon</th>
      <th>Clean</th>
      <th>Handicapped</th>
      <th>Near</th>
      <th>Supplies</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @baths.each do |bath| %>
      <tr>
        <td><%= bath.name %></td>
        <td><%= bath.lat %></td>
        <td><%= bath.lon %></td>
        <td><%= bath.clean %></td>
        <td><%= bath.handicapped %></td>
        <td><%= bath.near %></td>
        <td><%= bath.supplies %></td>
        <td><%= link_to 'Show', bath %></td>
        <td><%= link_to 'Edit', edit_bath_path(bath) %></td>
        <td><%= link_to 'Destroy', bath, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bath', new_bath_path %>
<%= link_to "Go back", "/" %>

app/views/baths/new.html.erb
<h1>New Bath</h1>

<%= render 'form', bath: @bath %>

<%= link_to 'Back', baths_path %>

app/views/baths/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @bath.name %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @bath.lat %>
</p>

<p>
  <strong>Lon:</strong>
  <%= @bath.lon %>
</p>

<p>
  <strong>Clean:</strong>
  <%= @bath.clean %>
</p>

<p>
  <strong>Handicapped:</strong>
  <%= @bath.handicapped %>
</p>

<p>
  <strong>Near:</strong>
  <%= @bath.near %>
</p>

<p>
  <strong>Supplies:</strong>
  <%= @bath.supplies %>
</p>

<%= link_to 'Edit', edit_bath_path(@bath) %> |
<%= link_to 'Back', baths_path %>

app/views/info/result.html.erb
<h1>You have to go</h1>

<%#<%= @curLat %>
<%# <%= @lat %> 
<%# <%= @k %> 
<p> ' New Engineering Hall '</p>

<%= link_to "Go back", "/" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlgoAssign</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <div id="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    <% end %>
    <%= yield %>
  </div>
</html>